version: '3'
services:
  mysql:
    build:
      context: ./docker-config
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sluggrid
      MYSQL_DATABASE: microgridManager
      MYSQL_USER: microgridManager
      MYSQL_PASSWORD: sluggrid
