version: '3'
services:
  front-end:
    build: ./frontend
    container_name: Dashboard
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  interface_0:
    build: ./interfaces/Example
    container_name: example-python-microservice
    volumes:
      - ./interfaces/Example:/app
  mysql:
    build:
      context: ./docker-config
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sluggrid
      MYSQL_DATABASE: microgridManager
      MYSQL_USER: microgridManager
      MYSQL_PASSWORD: sluggrid
      
