FROM mysql:latest

# Environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=sluggrid
ENV MYSQL_DATABASE=microgridManager
ENV MYSQL_USER=microgridManager
ENV MYSQL_PASSWORD=sluggrid

# Expose the MySQL port
EXPOSE 3306
