version: '3'
services:
  frontend:
    image: ejx537/frontend:latest
    container_name: Dashboard
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true
    pull_policy: always
  
  backend:
    image: ejx537/backend:latest
    container_name: backend
    ports:
      - '8080:8080'
    pull_policy: always

  mysql:
    image: ejx537/mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sluggrid
      MYSQL_DATABASE: microgridManager
      MYSQL_USER: microgridManager
      MYSQL_PASSWORD: sluggrid
    volumes:
      - mysql-data:/var/lib/mysql
    pull_policy: always
    
  interface_0:
    image: ejx537/egauge:latest
    container_name: egauge_API_db
    pull_policy: always
    depends_on:
      - mysql

  interface_1:
    image: ejx537/powerview:latest
    container_name: powerview
    pull_policy: always
    depends_on:
      - mysql

volumes:
  mysql-data:
  
