name: Microgrid Manager

on:
  workflow_dispatch:
  push:
    branches: [ "test-deployment" ]
  pull_request:
    branches: [ "test-deployment" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: test-deployment
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Build and push Docker image
      run: |
        REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        docker-compose build frontend
        docker tag frontend docker.pkg.github.com/$REPO_LOWER/frontend:latest
        docker push docker.pkg.github.com/$REPO_LOWER/frontend:latest
