name: Microgrid Manager

on:
  workflow_dispatch:
  push:
    branches: [ "test-deployment" ]
  pull_request:
    branches: [ "test-deployment" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: test-deployment
    - name: Build the Docker image
      run: docker-compose build . --file dockercompose.yaml Microgrid-Manager:$(date +%s)
