name: Microgrid Manager

on:
  workflow_dispatch:
  push:
    branches: [ "test-deployment" ]
  pull_request:
    branches: [ "test-deployment" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: test-deployment
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker images
      run: |
        docker-compose build
        docker tag microgrid_frontend docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
        docker tag microgrid_backend docker.io/${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
        docker tag microgrid_mysql docker.io/${{ secrets.DOCKERHUB_USERNAME }}/mysql:latest
        docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
        docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

