name: Microgrid Manager

on:
  workflow_dispatch:
  push:
    branches: [ "test-deployment" ]
  pull_request:
    branches: [ "test-deployment" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: test-deployment
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      run: |
        REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        docker-compose build frontend
        docker tag microgrid_frontend ghcr.io/$REPO_LOWER/frontend:latest
        docker push ghcr.io/$REPO_LOWER/frontend:latest
